
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883/tcp"  # MQTT порт
      - "9001:9001"  # MQTT WebSocket порт (опционально)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config:/mosquitto/config  # Конфигурация Mosquitto
      - ./mosquitto/data:/mosquitto/data  # Данные Mosquitto
      - ./mosquitto/log:/mosquitto/log  # Логи Mosquitto
    networks:
      - sensor_network

  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - sensor_network

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - sensor_network

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - sensor_network

volumes:
  grafana-storage:
  influxdb-storage:

# Сеть для взаимодействия контейнеров
networks:
  sensor_network:
    driver: bridge